move env variables

diff --git a/.github/workflows/docker-compose-local.yml b/.github/workflows/docker-compose-local.yml
--- a/.github/workflows/docker-compose-local.yml
+++ b/.github/workflows/docker-compose-local.yml
@@ -9,20 +9,6 @@ on:
       - main
   workflow_dispatch:
 
-env:
-  MYSQL_DATABASE: chatdb
-  MYSQL_LOCAL_PORT: 3307
-  MYSQL_DOCKER_PORT: 3306
-  NODE_PORT: 5005
-  MYSQL_USER: chatuser
-  CLIENT_PORT: 3000
-  USERDB_MYSQL_DATABASE: userdb
-  USERDB_MYSQL_LOCAL_PORT: 3307
-  USERDB_MYSQL_DOCKER_PORT: 3307
-  USERDB_MYSQL_USER: userdbuser
-  BACKEND_ENTRYPOINT: http://localhost
-  CORS_ORIGIN: http://localhost:3000
-
 jobs:
   build-and-run:
     runs-on: ubuntu-latest
@@ -34,13 +20,13 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-      - name: Check that .env File does not exist yet
-        run: |
-          if [ -f .env ]; then
-            echo "❌ ERROR: .env file found!"
-            exit 1
-          fi
-          echo "✅ .env file not found. Proceeding..."
+      # - name: Check that .env File does not exist yet
+      #   run: |
+      #     if [ -f .env ]; then
+      #       echo "❌ ERROR: .env file found!"
+      #       exit 1
+      #     fi
+      #     echo "✅ .env file not found. Proceeding..."
 
       - name: Install Docker Compose
         run: |
@@ -48,17 +34,26 @@ jobs:
           sudo apt-get install -y docker-compose
           docker-compose --version
 
-      - name: Create Temporary .env File
-        run: |
-          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
-          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
-          echo "USERDB_MYSQL_ROOT_PASSWORD=${{ secrets.USERDB_MYSQL_ROOT_PASSWORD }}" >> .env
-          echo "USERDB_MYSQL_PASSWORD=${{ secrets.USERDB_MYSQL_PASSWORD }}" >> .env
-          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
-          echo "✅ .env file created."
-
       - name: Build and Start Services
-        run: docker-compose --env-file .env up -d --build
+        run: docker-compose up --build
+        env:
+          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
+          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
+          USERDB_MYSQL_ROOT_PASSWORD: ${{ secrets.USERDB_MYSQL_ROOT_PASSWORD }}
+          USERDB_MYSQL_PASSWORD: ${{ secrets.USERDB_MYSQL_PASSWORD }}
+          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
+          MYSQL_DATABASE: chatdb
+          MYSQL_LOCAL_PORT: 3307
+          MYSQL_DOCKER_PORT: 3306
+          NODE_PORT: 5005
+          MYSQL_USER: chatuser
+          CLIENT_PORT: 3000
+          USERDB_MYSQL_DATABASE: userdb
+          USERDB_MYSQL_LOCAL_PORT: 3307
+          USERDB_MYSQL_DOCKER_PORT: 3307
+          USERDB_MYSQL_USER: userdbuser
+          BACKEND_ENTRYPOINT: http://localhost
+          CORS_ORIGIN: http://localhost:3000
 
       - name: Show Running Containers
         run: docker ps
