revert and delete env variables in the beginning

diff --git a/.github/workflows/docker-compose-local.yml b/.github/workflows/docker-compose-local.yml
--- a/.github/workflows/docker-compose-local.yml
+++ b/.github/workflows/docker-compose-local.yml
@@ -20,16 +20,13 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-      # - name: Check that .env File does not exist yet
-      #   run: |
-      #     if [ -f .env ]; then
-      #       echo "❌ ERROR: .env file found!"
-      #       exit 1
-      #     fi
-      #     echo "✅ .env file not found. Proceeding..."
-
-      - name: Delete env file if it exists
-        run: rm -f .env && rm -f .env-sample
+      - name: Check that .env File does not exist yet
+        run: |
+          if [ -f .env ]; then
+            echo "❌ ERROR: .env file found!"
+            exit 1
+          fi
+          echo "✅ .env file not found. Proceeding..."
 
       - name: Install Docker Compose
         run: |
@@ -37,26 +34,29 @@ jobs:
           sudo apt-get install -y docker-compose
           docker-compose --version
 
+      - name: Create Temporary .env File
+        run: |
+          echo "MYSQL_DATABASE=${MYSQL_DATABASE}" >> .env
+          echo "MYSQL_LOCAL_PORT=${MYSQL_LOCAL_PORT}" >> .env
+          echo "MYSQL_DOCKER_PORT=${MYSQL_DOCKER_PORT}" >> .env
+          echo "NODE_PORT=${NODE_PORT}" >> .env
+          echo "MYSQL_USER=${MYSQL_USER}" >> .env
+          echo "CLIENT_PORT=${CLIENT_PORT}" >> .env
+          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
+          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
+          echo "USERDB_MYSQL_DATABASE=${USERDB_MYSQL_DATABASE}" >> .env
+          echo "USERDB_MYSQL_LOCAL_PORT=${USERDB_MYSQL_LOCAL_PORT}" >> .env
+          echo "USERDB_MYSQL_DOCKER_PORT=${USERDB_MYSQL_DOCKER_PORT}" >> .env
+          echo "USERDB_MYSQL_USER=${USERDB_MYSQL_USER}" >> .env
+          echo "USERDB_MYSQL_ROOT_PASSWORD=${{ secrets.USERDB_MYSQL_ROOT_PASSWORD }}" >> .env
+          echo "USERDB_MYSQL_PASSWORD=${{ secrets.USERDB_MYSQL_PASSWORD }}" >> .env
+          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
+          echo "BACKEND_ENTRYPOINT=${BACKEND_ENTRYPOINT}" >> .env
+          echo "CORS_ORIGIN=${CORS_ORIGIN}" >> .env
+          echo "✅ .env file created."
+
       - name: Build and Start Services
-        run: docker-compose up --build
-        env:
-          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
-          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
-          USERDB_MYSQL_ROOT_PASSWORD: ${{ secrets.USERDB_MYSQL_ROOT_PASSWORD }}
-          USERDB_MYSQL_PASSWORD: ${{ secrets.USERDB_MYSQL_PASSWORD }}
-          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
-          MYSQL_DATABASE: chatdb
-          MYSQL_LOCAL_PORT: 3307
-          MYSQL_DOCKER_PORT: 3306
-          NODE_PORT: 5005
-          MYSQL_USER: chatuser
-          CLIENT_PORT: 3000
-          USERDB_MYSQL_DATABASE: userdb
-          USERDB_MYSQL_LOCAL_PORT: 3307
-          USERDB_MYSQL_DOCKER_PORT: 3307
-          USERDB_MYSQL_USER: userdbuser
-          BACKEND_ENTRYPOINT: http://localhost
-          CORS_ORIGIN: http://localhost:3000
+        run: docker-compose --env-file .env up -d --build
 
       - name: Show Running Containers
         run: docker ps
